version: '2.2'

services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=mypass
    volumes:
      - db-data:/var/log/mysql
  wp:
    image: wordpress
    links:
      - db
    deploy:
     resources:
      limits:
       cpus: '0.50'

    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=mypass
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wp-data:/var/www/html
    ports:
      - 80:80
volumes:
   db-data:
      driver: local
   wp-data:
      driver: local
